// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhNiDIsoSIN57PNupE2smjG1M_mXIDHXs',
    appId: '1:741746818037:web:a2b19e37824b911c4c7ebc',
    messagingSenderId: '741746818037',
    projectId: 'apple---ecommerce',
    authDomain: 'apple---ecommerce.firebaseapp.com',
    storageBucket: 'apple---ecommerce.appspot.com',
    measurementId: 'G-TR51KZ2D9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYz10sL__LdXamohtnIBvCgcBu6rliMo',
    appId: '1:741746818037:android:bd3c648c75a696fa4c7ebc',
    messagingSenderId: '741746818037',
    projectId: 'apple---ecommerce',
    storageBucket: 'apple---ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsmsyErUNuKF5R6gU2ukvZWYLx2htdiqs',
    appId: '1:741746818037:ios:616a6bd100c78cba4c7ebc',
    messagingSenderId: '741746818037',
    projectId: 'apple---ecommerce',
    storageBucket: 'apple---ecommerce.appspot.com',
    iosBundleId: 'lk.migara.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsmsyErUNuKF5R6gU2ukvZWYLx2htdiqs',
    appId: '1:741746818037:ios:716dda44b9d1a0784c7ebc',
    messagingSenderId: '741746818037',
    projectId: 'apple---ecommerce',
    storageBucket: 'apple---ecommerce.appspot.com',
    iosBundleId: 'com.example.appleEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhNiDIsoSIN57PNupE2smjG1M_mXIDHXs',
    appId: '1:741746818037:web:30bf4471797585754c7ebc',
    messagingSenderId: '741746818037',
    projectId: 'apple---ecommerce',
    authDomain: 'apple---ecommerce.firebaseapp.com',
    storageBucket: 'apple---ecommerce.appspot.com',
    measurementId: 'G-R45RX511NE',
  );
}
